### ISSUE TITLE
你好hosts

### ISSUE THREAD

**Issue by zicheng53** [malaohu/GitHubHosts#1]
您好我今天测试了一下，您主机里的地址更换到我windows的hosts文件中，起初访问github速度特别快，但过了十分钟后就开始打不开github网页，而后删除您主机上的地址后，恢复了正常，不知道这是什么原因，所以想问问这是什么原因造成的，

**Comment by malaohu** [comment]
这应该是GFW的常规操作。其实不改HOSTS也能访问Github，但是访问一会就会访问不到，因为GFW干扰了。

**Comment by malaohu** [comment]
这应该是GFW的常规操作
